services:
  team4mation:
    build: ./backend
    container_name: team4mation_app
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env
    volumes:
      - ./frontend/dist:/frontend/dist
    restart: always

  php:
    image: php:8.2-apache
    container_name: team4mation_php
    ports:
      - "8000:80"
    volumes:
      - ./login:/var/www/html
    restart: always
    environment:
      - APP_URL=http://164.92.80.18:3001
    command: >
      bash -c "apt-get update && apt-get install -y libcurl4-openssl-dev && docker-php-ext-install curl && apache2-foreground"