services:
  team4mation:
    build: ./backend
    container_name: team4mation_app
    ports:
      - "3002:3001"
    env_file:
      - ./backend/.env
    volumes:
      - ./frontend/dist:/frontend/dist
    restart: always

  php:
    build: ./login
    container_name: team4mation_php
    ports:
      - "8000:80"
    volumes:
      - ./login:/var/www/html
    restart: always
    environment:
      - APP_URL=http://164.92.80.18:3001